apiVersion: v1
kind: Pod
metadata:
  name: pod-config-map-as-env1
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "env && sleep 3600"]
    envFrom:
      - configMapRef:
          name: game-config
