apiVersion: v1
kind: Pod
metadata:
  name: pod-config-map-as-env
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo $(LOG_LEVEL) && sleep 3600"]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: myappconfig
          key: log_level
