apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-as-vol
spec:
  containers:
  - name: pod-with-secret-as-vol
    image: busybox
    command: ['sh', '-c', "echo $(ls /etc/foo) && sleep 3600"]
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
