apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-as-env1
spec:
  containers:
  - name: pod-with-secret-as-env1
    image: busybox
    command: ['sh', '-c', "echo $(env) && sleep 3600"]
    envFrom:
      - secretRef:
          name: mysecret
