apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-as-env
spec:
  containers:
  - name: pod-with-secret-as-env
    image: busybox
    command: ['sh', '-c', "echo $(env) && sleep 3600"]
    env:
    - name: USER_NAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
