apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-fixed-count-job
spec:
  completions: 4
  template:
    spec:
      containers:
      - name: parallel-fixed-count-job
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
